"use client";

import React, { useState, useRef } from "react";
import { motion } from "framer-motion";
import { Icon } from "@iconify/react";
import { ApparelInputForm } from "@/components/apparel-agent/ApparelInputForm";
import { AgentPipelineTracker } from "@/components/apparel-agent/AgentPipelineTracker";
import { StructuredOutputPanel } from "@/components/apparel-agent/StructuredOutputPanel";
import { type ApparelResponse, type MultiAgentPhase } from "@/types/apparel";
import { toast } from "sonner";

export default function ApparelAgentPage() {
  const [phase, setPhase] = useState<MultiAgentPhase>("idle");
  const [result, setResult] = useState<ApparelResponse | null>(null);
  const abortControllerRef = useRef<AbortController | null>(null);

  const handleGenerate = async (formData: { category: string; targetAudience: string; images: File[] }) => {
    if (abortControllerRef.current) abortControllerRef.current.abort();
    const controller = new AbortController();
    abortControllerRef.current = controller;

    setResult(null);
    setPhase("idle");

    try {
      const response = await fetch("/api/apparel-agent/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          category: formData.category,
          targetAudience: formData.targetAudience,
          images: formData.images.map(f => f.name)
        }),
        signal: controller.signal,
      });

      if (!response.ok || !response.body) throw new Error("API call failed");

      const reader = response.body.getReader();
      const decoder = new TextDecoder();

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        const chunk = decoder.decode(value, { stream: true });
        const lines = chunk.split("\n").filter(Boolean);

        for (const line of lines) {
          if (line.startsWith("d:")) {
            try {
              // Extract the JSON payload generated by dataStream.writeData in Vercel AI SDK
              const parsedArray = JSON.parse(line.slice(2));
              // Vercel AI SDK 3.x wraps single data writes in an array, or it might just be the object depending on the version. Let's handle both.
              const data = Array.isArray(parsedArray) ? parsedArray[0] : parsedArray;
              
              if (data?.type === "phase") {
                setPhase(data.phase);
              } else if (data?.type === "result") {
                setResult(data.data);
                toast.success("策划全案生成完毕！");
              }
            } catch {
              console.error("Failed to parse stream chunk:", line);
            }
          } else if (line.startsWith("e:")) {
            throw new Error("Steam error from AI SDK");
          }
        }
      }

    } catch (err: unknown) {
      if (err instanceof Error && err.name !== "AbortError") {
        console.error(err);
        setPhase("failed");
        toast.error("生成失败，请重试");
      } else if (!(err instanceof Error)) {
        console.error(err);
        setPhase("failed");
      }
    } finally {
      abortControllerRef.current = null;
    }
  };

  const handleStop = () => {
    if (abortControllerRef.current) {
      abortControllerRef.current.abort();
      abortControllerRef.current = null;
    }
    setPhase("idle");
    toast.info("已终止生成任务");
  };

  return (
    <div className="flex flex-col lg:flex-row h-screen p-4 md:p-6 lg:p-8 gap-6 overflow-hidden bg-zinc-950">
      
      {/* Left Panel - Input */}
      <motion.div
        initial={{ opacity: 0, x: -20 }}
        animate={{ opacity: 1, x: 0 }}
        className="w-full lg:w-[400px] shrink-0 overflow-y-auto custom-scrollbar rounded-2xl border border-white/10 bg-white/5 p-6 backdrop-blur-xl flex flex-col"
      >
        <div className="mb-6">
          <h1 className="text-2xl font-bold text-white tracking-tight">Apparel Agent</h1>
          <p className="text-sm text-zinc-400 mt-1">服装详情页多智能体工作流</p>
        </div>
        
        <ApparelInputForm 
          onGenerate={handleGenerate} 
          isGenerating={phase !== "idle" && phase !== "completed" && phase !== "failed"} 
          onStop={handleStop}
        />
      </motion.div>

      {/* Right Panel - Progress & Output */}
      <motion.div
        initial={{ opacity: 0, x: 20 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ delay: 0.1 }}
        className="flex-1 flex flex-col gap-6 overflow-hidden"
      >
        {/* Top: Multi-Agent Pipeline Visualization (Always visible or shows status) */}
        <div className="shrink-0">
          <AgentPipelineTracker currentPhase={phase} />
        </div>

        {/* Bottom: Structured Output */}
        <div className="flex-1 overflow-hidden rounded-2xl border border-white/10 bg-black/20 backdrop-blur-xl relative">
          {phase === "idle" && !result && (
            <div className="absolute inset-0 flex flex-col items-center justify-center text-zinc-500">
              <Icon icon="lucide:bot" className="h-10 w-10 mb-4 opacity-50" />
              <p>等待输入信息以启动智能体矩阵</p>
            </div>
          )}
          
          {phase === "failed" && !result && (
            <div className="absolute inset-0 flex flex-col items-center justify-center text-red-400">
              <Icon icon="lucide:alert-triangle" className="h-10 w-10 mb-4" />
              <p>任务中断或发生错误</p>
            </div>
          )}

          {result && phase === "completed" && (
            <StructuredOutputPanel data={result} />
          )}
        </div>
      </motion.div>
    </div>
  );
}
